### ISSUE TITLE
BUG: "Clip Highlights" Button Not Working in Vivaldi

### ISSUE THREAD

**Issue by nihitkhandelwal-eng** [obsidianmd/obsidian-clipper#285]
**Version: 0.10.5** 

- OS: Windows
- Browser: Vivaldi
- Web Clipper version: 0.10.5
- Obsidian version: 1.7.7

**Describe the bug**
After highlighting any element using the highlighter mode, the button "Clip Highlights" is not working, however if the extension icon for obsidian web clipper is clicked, the highlighted elements are clipped

**Expected behavior**
After clicking on "Clip Highlights", the extension popup appears 

**URLs where the bug occurs**
No specific pages, i.e. it happens across all pages

**To reproduce**

1. Go to any webpage
2. Enable highlighter mode
3. Highlight a few elements
4. Click on "Clip Highlights"
5. See error

**Your template file**
Default template
Even tried with an empty template

**Comment by mtissington** [comment]
Here is the error when clicking the button

```
content.js:1 Error opening popup: Error: Browser window has no toolbar.
    at HTMLButtonElement.<anonymous> (content.js:1:26122)
    at Generator.next (<anonymous>)
    at o (content.js:1:22972)
(anonymous) @ content.js:1
o @ content.js:1
Promise.then
l @ content.js:1
o @ content.js:1
Promise.then
l @ content.js:1
(anonymous) @ content.js:1
H @ content.js:1
X @ content.js:1

```

**Comment by mickbed** [comment]
Same issue here

Vivaldi	7.1.3570.50 (Stable channel) (64-bit) 
Revision	38ed95b8fe18fffe5e88e77cda0c8aa9a87d73d6
OS	Windows 11 Version 24H2 (Build 26100.3194)
JavaScript	V8 13.2.152.40
Webclipper: Version 0.10.8
Obsidian version: 1.8.4

**Comment by KraXen72** [comment]
Same issue here
```
Vivaldi	7.1.3570.50 (Stable channel) stable (64-bit) 
Revision	38ed95b8fe18fffe5e88e77cda0c8aa9a87d73d6
OS	Linux
JavaScript	V8 13.2.152.40
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
Command Line	/usr/bin/vivaldi-stable --flag-switches-begin --flag-switches-end --save-page-as-mhtml
Executable Path	/opt/vivaldi/vivaldi
Profile Path	/home/nex/.config/vivaldi/Default
```
clipper version: 0.10.8
obsidian version: 1.8.4 on installer 1.8.3

**Comment by fcherini** [comment]
Still happening for me

**Comment by kepano** [comment]
This issue is open to PRs

**Comment by imadreamerboy** [comment]
I can take a look at the vivaldi bugs this week including #430 and #437

**Comment by imadreamerboy** [comment]
We can't open the popup because there exists no "toolbar" in vivaldi, i addressed this by enabling it through the sidebar, which works.
